### ISSUE TITLE
Preparation of Training Data and Missing File Issue

### ISSUE THREAD

**Issue by fighting-Zhang** [whaohan/pivotmesh#3]
Thank you for sharing the code; it has been very inspiring! 

Could you please advise on how I should prepare the training data? Is there a corresponding script for this purpose?

FileNotFoundError: [Errno 2] No such file or directory: './data/objaverse-lp-500/train-500'

**Comment by whaohan** [comment]
Just put all the training mesh on such directory and ensure that the faces of these meshes are lower than a the max face (e.g., 500).
