### ISSUE TITLE
测试集信息泄露

### ISSUE THREAD

**Issue by Costwen** [whaohan/pivotmesh#5]
![image](https://github.com/user-attachments/assets/2c82d2de-4ec2-4a96-8de8-7d95a40403e5)
我注意到在推理的时候，这个地方的tokenizer，实际上用了是全局的mesh信息来tokenize的，但实际上你在pivot推理的时候是没办法拿到这个信息的。这个地方是有问题的

**Comment by whaohan** [comment]
Basically, Pivotmesh is an unconditional generation method like MeshGPT. At inference, it first generates pivot vertices and then generates the full mesh sequence.

At current unconditional setting, the pivot vertices can only be generated by model or extracted from another mesh. If you want to perform conditional generation (e.g., point cloud conditioned mesh generation), feel free to add point cloud condition based on PivotMesh via cross-attention or prefix condition.

**Comment by ch1998** [comment]
> Basically, Pivotmesh is an unconditional generation method like MeshGPT. At inference, it first generates pivot vertices and then generates the full mesh sequence.
> 
> At current unconditional setting, the pivot vertices can only be generated by model or extracted from another mesh. If you want to perform conditional generation (e.g., point cloud conditioned mesh generation), feel free to add point cloud condition based on PivotMesh via cross-attention or prefix condition.

When performing conditional generation, it is necessary to load a dataset. Can i directly load the given point cloud to infer?

**Comment by whaohan** [comment]
PivotMesh cannot load the point cloud directly to generate a mesh. You should first train PivotMesh with point cloud condition, then you can load point cloud to infer.

**Comment by Guest400123064** [comment]
> PivotMesh cannot load the point cloud directly to generate a mesh. You should first train PivotMesh with point cloud condition, then you can load point cloud to infer.

Does that mean the condition-to-pivot generation model is not currently available? In other words, does that mean the only way to generate the results presented in the paper is to condition on pre-extracted pivot vertices?
